swagger: '2.0'
info:
  description: This is the API exposed by DUE-VDM
  version: 1.0.0
  title: DUE-VDM API
  # put the contact info for your development or API team
  contact:
    email: mirco.manzoni@mail.polimi.it

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: debug
  description: Check the status of the component

paths:
  /debug/:
    get:
      tags:
      - debug
      summary: Debug hello world
      produces:
      - application/json
      responses:
        404:
          description: Not Found
        200:
          description: search results matching criteria
          schema:
            type: object
            properties:
              msg:
                type: string
        400:
          description: bad input parameter
  /debug/vdcs:
    get:
      tags:
      - debug
      summary: Get all the VDCs the DUE-VDM monitor
      produces:
      - application/json
      responses:
        404:
          description: Not Found
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
               type: string
        400:
          description: bad input parameter
  /debug/{vdc}/methods:
    get:
      tags:
      - debug
      summary: Get all the methods monitored related to
               the given {vdc}
      produces:
      - application/json
      parameters:
      - in: path
        name: vdc
        required: true
        type: string
      responses:
        404:
          description: Not Found
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
               type: string
        400:
          description: bad input parameter

# Host and schemes dynamically retrieved if not set
# host: virtserver.swaggerhub.com
# schemes:
#  - https
#basePath: /rest
